accounts/urls.py
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.Register.as_view(), name='register'),
    path('profile', views.profile, name='profile'),
    path('contact',views.contact, name='contact')
]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_details, name="cart_details"),
    path('add', views.add_to_cart, name="add"),
    path('remove/<int:id>', views.remove_from_cart, name="remove"),
    path('clear/', views.clear_cart, name="clear")
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('place', views.CreateOrder.as_view(), name='place'),
    path('my', views.MyOrders.as_view(), name='my'),
    path('details/<int:pk>/', views.OrderDetails.as_view(), name='details'),
    path('invoice/<int:pk>/', views.OrderInvoice.as_view(), name='invoice')
]

store/urls.py
from django.urls import path
from store import views

app_name = 'store'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product_list'),
    path('categories', views.CategoriesList.as_view(), name='categories_list'),
    path('product/<slug:slug>/', views.ProdcutDetails.as_view(),
         name='product_details'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.forms import modelform_factory, widgets
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

# Create your views here.


class Register(SuccessMessageMixin, generic.CreateView):
    form_class = UserCreationForm
    success_message = "Registration Successfull you can now login."
    template_name = "registration/register.html"
    success_url = reverse_lazy('login')


@login_required
def profile(req):
    UserEditForm = modelform_factory(
        get_user_model(), fields=('first_name', 'last_name', 'username'))
    form = UserEditForm(instance=req.user)
    if req.method == "POST":
        form = UserEditForm(instance=req.user, data=req.POST)
        if form.is_valid():
            form.save()
    return render(req, 'registration/profile.html', {'form': form})

def contact(req):
    UserEditForm = modelform_factory(
        get_user_model(), fields=('first_name', 'last_name', 'username'))
    form = UserEditForm(instance=req.user)
    if req.method == "POST":
        form = UserEditForm(instance=req.user, data=req.POST)
        if form.is_valid():
            form.save()
    return render(req, 'registration/contact.html', {'form': form})

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <nav class="navbar navbar-dark  navbar-expand-lg" style="background-color: #4d4dff;">
      <div class="container">
        <a href="{% url 'store:product_list' %}" class="navbar-brand">ONL SHOP</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navigation">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="{% url 'store:product_list' %}" class="nav-link">
                <i class="fa fa-shopping-bag fa-lg mr-1"></i> Shop
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'store:categories_list' %}" class="nav-link">
                <i class="fa fa-shopping-basket fa-lg mr-1"></i> Categories
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'contact'%}" class="nav-link">
                <i class="fa fa-twitch"></i> Contact
              </a>
            </li>
          </ul>
          <form action="/" class="inline-form mr-md-2 ml-auto">
            <div class="input-group">
              <input
                required
                type="text"
                name="name"
                placeholder="Search"
                class="form-control"
              />
              <div class="input-group-append">
                <button type="submit" class="btn-success btn btn-sm">
                  <i class="fa fa-search fa-lg"></i>
                </button>
              </div>
            </div>
          </form>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'orders:my' %}" class="nav-link">
                <i class="fa fa-truck fa-lg mr-1"></i> Order
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'cart:cart_details' %}" class="nav-link">
                <i class="fa fa-shopping-cart fa-lg"></i>
                <span class="badge badge-secondary">
                  {% if cart %} {{cart|length}} {% else %} 0 {% endif%}
                </span>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle mb-0"
                data-toggle="dropdown"
              >
                {{request.user}}
              </a>
              <div class="dropdown-menu">
                <a href="{% url 'profile'%}" class="dropdown-item">Personal Information </a>
                <a href="{% url 'password_change'%}" class="dropdown-item">
                  Change Password
                </a>
                <a href="{% url 'logout' %}" class="dropdown-item">Log out </a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">
                <i class="fa fa-sign-in fa-lg"></i> Log in
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'register' %}" class="nav-link">
                <i class="fa fa-user-plus fa-lg"></i> Register
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    
    <div class="container">
      {% if messages %}
      <div class="alert alert-success my-2">
        {% for message in messages %} {{message}} {% endfor %}
      </div>
      {% endif %} {% block content %} {% endblock content %}
    </div>

    <footer class="container--fluid text-center text-lg-start text-muted mt-5">
      <!-- Section: Links  -->
      <section class="">
        <div class="container text-center text-md-start pt-4 pb-4">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-12 col-lg-3 col-sm-12 mb-2">
              <!-- Content -->
              <a href="{% url 'store:product_list' %}" target="_blank" class="text-red h2">
                <br>
                ONL SHOP
              </br>
              </a>
              <p class="mt-1 text-black">
                © 2023 Copyright: ONLshop.com
              </p>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-6 col-sm-4 col-lg-2">
              <!-- Links -->
              <h6 class="text-uppercase text-black fw-bold mb-2">
                Store
              </h6>
              <ul class="list-unstyled mb-4">
                <li><a class="text-black-50" href="#">About us</a></li>
                <li><a class="text-black-50" href="#">Find store</a></li>
                <li><a class="text-black-50" href="#">Categories</a></li>
                <li><a class="text-balck-50" href="#">Blogs</a></li>
              </ul>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-6 col-sm-4 col-lg-2">
              <!-- Links -->
              <h6 class="text-uppercase text-black fw-bold mb-2">
                Information
              </h6>
              <ul class="list-unstyled mb-4">
                <li><a class="text-black-50" href="#">Help center</a></li>
                <li><a class="text-black-50" href="#">Money refund</a></li>
                <li><a class="text-black-50" href="#">Shipping info</a></li>
                <li><a class="text-black-50" href="#">Refunds</a></li>
              </ul>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-6 col-sm-4 col-lg-2">
              <!-- Links -->
              <h6 class="text-uppercase text-black fw-bold mb-2">
                Support
              </h6>
              <ul class="list-unstyled mb-4">
                <li><a class="text-black-50" href="#">Help center</a></li>
                <li><a class="text-black-50" href="#">Documents</a></li>
                <li><a class="text-black-50" href="#">Account restore</a></li>
                <li><a class="text-black-50" href="#">My orders</a></li>
              </ul>
            </div>
            <!-- Grid column -->
    
            <!-- Grid column -->
            <div class="col-12 col-sm-12 col-lg-3">
              <!-- Links -->
              <h6 class="text-uppercase text-black fw-bold mb-2">Newsletter</h6>
              <p class="text-black">Stay in touch with latest updates about our products and offers</p>
              <div class="input-group mb-3">
                <input type="email" class="form-control border" placeholder="Email" aria-label="Email" aria-describedby="button-addon2" />
                <button class="btn btn-light border shadow-0" type="button" id="button-addon2" data-mdb-ripple-color="dark">
                  Join
                </button>
              </div>
            </div>
            <!-- Grid column -->
           <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->
    
      <div class="">
        <div class="container">
          <div class="d-flex justify-content-between py-4 border-top">
            <!-- payment -->
            <div>
              <i class="fa fa-cc-visa text-dark" style="font-size:24px"></i>
              <i class="fa fa-cc-amex text-dark" style="font-size:24px"></i>
              <i class="fa fa-cc-mastercard text-dark" style="font-size:24px"></i>
              <i class="fa fa-cc-paypal text-dark" style="font-size:24px"></i>
            </div>
            <!-- payment -->
    
            <!-- language selector -->
            <div class="dropdown dropup">
              <a class="dropdown-toggle text-black" href="#" id="Dropdown" role="button" data-mdb-toggle="dropdown" aria-expanded="false"> <i class="flag-united-kingdom flag m-0 me-1"></i>English </a>
    
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="Dropdown">
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-united-kingdom flag"></i>English <i class="fa fa-check text-success ms-2"></i></a>
                </li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-poland flag"></i>Polski</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-china flag"></i>中文</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-japan flag"></i>日本語</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-germany flag"></i>Deutsch</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-france flag"></i>Français</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-spain flag"></i>Español</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-russia flag"></i>Русский</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#"><i class="flag-portugal flag"></i>Português</a>
                </li>
              </ul>
            </div>
            <!-- language selector -->
          </div>
        </div>
      </div>
      <div class="">
        <div class="container">
          <div class="d-flex justify-content-between py-4 border-top">
    <script src="{% static 'app/js/cart.js' %}"> </script>      <!--muc dich la de load san pham roi moi load js-->
          </div>
        </div>
      </div>

  </footer>   

  </body>
</html>